name: Code Coverage check

on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' 
      && contains(github.event.comment.html_url, '/pull/')  
      && contains(github.event.comment.body, '/checkCoverage')) }}

    name: Check test coverage

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: ./gradlew build jacocoTestCoverageVerification -PenableCodeCoverage=true

    - name: Summarize results
      run: |
        python config/transformJacocoResult.py
        cat build/reports/jacoco/test/output_table.html >> $GITHUB_STEP_SUMMARY

    - name: Comment
      if: ${{ github.event_name == 'issue_comment' }}
      env:
        PR_NUMBER: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ github.token }}
      run: |
        content=$(cat build/reports/jacoco/test/output_table.html)
        gh pr comment $PR_NUMBER --body "$content"

    - name: Upload coverage result
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/jacoco/
